version: "3.4"
services:
  server:
    image: nominator
    depends_on:
      - postgres
    build:
      context: ./api
      dockerfile: ./Dockerfile
    command: 'npm run dev'
    ports:
      - '9000:9000'
    volumes:
      - ./api:/usr/server
    environment:
      - DATABASE_URL=postgres://postgres:password@postgres/nominator
  client:
    image: client_nominator
    build:
      context: ./client
      dockerfile: ./Dockerfile
    command: npm run start
    volumes:
      - ./client:/usr/client
    ports: 
      - 9001:3000
  postgres:
    image: postgres
    environment:
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nominator